stages:
  - lint
  - test
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

include:
  - template: Jobs/Docker.gitlab-ci.yml

lint:
  stage: lint
  image: python:3.9
  script:
    - pip install flake8 black
    - black --check .
    - flake8 .

test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - python -m pytest tests/

build-package:
  stage: build
  image: python:3.9
  script:
    - pip install build twine
    - python -m build
    - python -m twine upload dist/*
  only:
    - main

pages:
  stage: deploy
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pip install quarto
    - quarto render README.md
    - mkdir public
    - mv README.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - main

docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  only:
    - main