stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/credit-default-analysis

docker-build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker tag $DOCKER_IMAGE $CI_REGISTRY_IMAGE/credit-default-analysis:latest
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

flake8-lint:
  stage: test
  image: python:3.9
  script:
    - pip install flake8
    - flake8 . --count --select=E9,F63,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=15 --statistics
  except:
    - main

black-format:
  stage: test
  image: python:3.9
  script:
    - pip install black
    - black --check .
    - black .
  except:
    - main

pypi-deploy:
  stage: deploy
  image: python:3.9
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - main
  except:
    - main

build-documentation:
  stage: deploy
  image: jupyter/minimal-notebook
  script:
    - jupyter nbconvert --to html notebooks/eda.ipynb --output-dir public
  artifacts:
    paths:
      - public/
    expire_in: 1 hour
  only:
    - main
  except:
    - main
