name: Advanced MLOps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Lint and Test
        run: |
          pip install -r requirements.txt
          black --check .
          flake8 .
          pytest tests/

  docker-build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Расширенная сборка с BuildKit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Логин в реестр
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Сборка и публикация
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/mlops-project:latest
            ghcr.io/${{ github.repository }}/mlops-project:${{ github.sha }}

  security-scan:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      # Сканирование образа на уязвимости
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}/mlops-project:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
