name: MLOps CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint and format
      run: |
        pip install flake8 black
        flake8 .
        black --check .
    
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/
    
    - name: Build Docker image
      run: docker build -t mlops-project .
    
    - name: Generate EDA documentation
      run: |
        pip install jupyter
        jupyter nbconvert --to html eda.ipynb
